services:
  send.localhost:
    hostname: send.localhost
    build:
      context: ./send
  recv.localhost:
    hostname: recv.localhost
    build:
      context: ./recv
    command: postfix start-fg
